accuracy: 0.8833333333333333
activation: elu
filename: !!python/object/apply:pathlib.PosixPath
- /
- home
- user
- nycu-deep-learning-2023-spring
- lab3
- weights
- 2023-04-10-00-37-40.yaml
lr: 0.0001
model: EEGNet
optimizer: Adam
weight_decay: 0.1
