accuracy: 0.8231481481481482
activation: leaky_relu
filename: !!python/object/apply:pathlib.PosixPath
- /
- home
- user
- nycu-deep-learning-2023-spring
- lab3
- weights
- 2023-04-11-02-12-02.yaml
lr: 0.0001
model: deepconv
optimizer: Adam
weight_decay: 0.0
