accuracy: 0.8416666666666667
activation: elu
filename: !!python/object/apply:pathlib.PosixPath
- /
- home
- user
- nycu-deep-learning-2023-spring
- lab3
- weights
- 2023-04-10-00-41-31.yaml
lr: 0.0001
model: deepconv
optimizer: Adam
weight_decay: 0.1
