accuracy: 0.8712962962962963
activation: relu
filename: !!python/object/apply:pathlib.PosixPath
- /
- home
- user
- nycu-deep-learning-2023-spring
- lab3
- weights
- 2023-04-11-01-56-25.yaml
lr: 0.0001
model: eegnet
optimizer: Adam
weight_decay: 0.0
