accuracy: 0.8861111111111111
activation: relu
filename: !!python/object/apply:pathlib.PosixPath
- /
- home
- user
- nycu-deep-learning-2023-spring
- lab3
- weights
- 2023-04-10-00-34-19.yaml
lr: 0.0001
model: EEGNet
optimizer: Adam
weight_decay: 0.1
